/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FindSimilarItemsRequest,
  GetIdxOfFileReqeust,
  GetIdxOfFileResponse,
  HTTPValidationError,
  LoadAllFilesResponse,
  SearchRequest,
  SearchResponse,
  SearchResultDTO,
} from '../models/index';
import {
    FindSimilarItemsRequestFromJSON,
    FindSimilarItemsRequestToJSON,
    GetIdxOfFileReqeustFromJSON,
    GetIdxOfFileReqeustToJSON,
    GetIdxOfFileResponseFromJSON,
    GetIdxOfFileResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LoadAllFilesResponseFromJSON,
    LoadAllFilesResponseToJSON,
    SearchRequestFromJSON,
    SearchRequestToJSON,
    SearchResponseFromJSON,
    SearchResponseToJSON,
    SearchResultDTOFromJSON,
    SearchResultDTOToJSON,
} from '../models/index';

export interface FindSimilarItemsLoadFindSimilarPostRequest {
    findSimilarItemsRequest: FindSimilarItemsRequest;
}

export interface GetDirectoryFilesLoadGetRequest {
    offset?: number;
    limit?: number;
}

export interface GetLoadIdxOfFileLoadGetLoadIndexPostRequest {
    getIdxOfFileReqeust: GetIdxOfFileReqeust;
}

export interface SearchLoadSearchPostRequest {
    searchRequest: SearchRequest;
    offset?: number;
    limit?: number;
}

/**
 * 
 */
export class LoadApi extends runtime.BaseAPI {

    /**
     * Find Similar Items
     */
    async findSimilarItemsLoadFindSimilarPostRaw(requestParameters: FindSimilarItemsLoadFindSimilarPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SearchResultDTO>>> {
        if (requestParameters['findSimilarItemsRequest'] == null) {
            throw new runtime.RequiredError(
                'findSimilarItemsRequest',
                'Required parameter "findSimilarItemsRequest" was null or undefined when calling findSimilarItemsLoadFindSimilarPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/load/find-similar`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FindSimilarItemsRequestToJSON(requestParameters['findSimilarItemsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SearchResultDTOFromJSON));
    }

    /**
     * Find Similar Items
     */
    async findSimilarItemsLoadFindSimilarPost(requestParameters: FindSimilarItemsLoadFindSimilarPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SearchResultDTO>> {
        const response = await this.findSimilarItemsLoadFindSimilarPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Directory Files
     */
    async getDirectoryFilesLoadGetRaw(requestParameters: GetDirectoryFilesLoadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoadAllFilesResponse>> {
        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/load/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoadAllFilesResponseFromJSON(jsonValue));
    }

    /**
     * Get Directory Files
     */
    async getDirectoryFilesLoadGet(requestParameters: GetDirectoryFilesLoadGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoadAllFilesResponse> {
        const response = await this.getDirectoryFilesLoadGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Load Idx Of File
     */
    async getLoadIdxOfFileLoadGetLoadIndexPostRaw(requestParameters: GetLoadIdxOfFileLoadGetLoadIndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetIdxOfFileResponse>> {
        if (requestParameters['getIdxOfFileReqeust'] == null) {
            throw new runtime.RequiredError(
                'getIdxOfFileReqeust',
                'Required parameter "getIdxOfFileReqeust" was null or undefined when calling getLoadIdxOfFileLoadGetLoadIndexPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/load/get-load-index`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetIdxOfFileReqeustToJSON(requestParameters['getIdxOfFileReqeust']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetIdxOfFileResponseFromJSON(jsonValue));
    }

    /**
     * Get Load Idx Of File
     */
    async getLoadIdxOfFileLoadGetLoadIndexPost(requestParameters: GetLoadIdxOfFileLoadGetLoadIndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetIdxOfFileResponse> {
        const response = await this.getLoadIdxOfFileLoadGetLoadIndexPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search
     */
    async searchLoadSearchPostRaw(requestParameters: SearchLoadSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResponse>> {
        if (requestParameters['searchRequest'] == null) {
            throw new runtime.RequiredError(
                'searchRequest',
                'Required parameter "searchRequest" was null or undefined when calling searchLoadSearchPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/load/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchRequestToJSON(requestParameters['searchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchResponseFromJSON(jsonValue));
    }

    /**
     * Search
     */
    async searchLoadSearchPost(requestParameters: SearchLoadSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResponse> {
        const response = await this.searchLoadSearchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
