/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  UpdateDescriptionRequest,
  UpdateTranscriptRequest,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    UpdateDescriptionRequestFromJSON,
    UpdateDescriptionRequestToJSON,
    UpdateTranscriptRequestFromJSON,
    UpdateTranscriptRequestToJSON,
} from '../models/index';

export interface UpdateDescriptionMetadataDescriptionPostRequest {
    updateDescriptionRequest: UpdateDescriptionRequest;
}

export interface UpdateTranscriptMetadataTranscriptPostRequest {
    updateTranscriptRequest: UpdateTranscriptRequest;
}

/**
 * 
 */
export class MetadataApi extends runtime.BaseAPI {

    /**
     * Update Description
     */
    async updateDescriptionMetadataDescriptionPostRaw(requestParameters: UpdateDescriptionMetadataDescriptionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['updateDescriptionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateDescriptionRequest',
                'Required parameter "updateDescriptionRequest" was null or undefined when calling updateDescriptionMetadataDescriptionPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/metadata/description`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateDescriptionRequestToJSON(requestParameters['updateDescriptionRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Description
     */
    async updateDescriptionMetadataDescriptionPost(requestParameters: UpdateDescriptionMetadataDescriptionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateDescriptionMetadataDescriptionPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Transcript
     */
    async updateTranscriptMetadataTranscriptPostRaw(requestParameters: UpdateTranscriptMetadataTranscriptPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['updateTranscriptRequest'] == null) {
            throw new runtime.RequiredError(
                'updateTranscriptRequest',
                'Required parameter "updateTranscriptRequest" was null or undefined when calling updateTranscriptMetadataTranscriptPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/metadata/transcript`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTranscriptRequestToJSON(requestParameters['updateTranscriptRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Transcript
     */
    async updateTranscriptMetadataTranscriptPost(requestParameters: UpdateTranscriptMetadataTranscriptPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateTranscriptMetadataTranscriptPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
