/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetIdxOfFileResponse
 */
export interface GetIdxOfFileResponse {
    /**
     * 
     * @type {number}
     * @memberof GetIdxOfFileResponse
     */
    idx: number;
}

/**
 * Check if a given object implements the GetIdxOfFileResponse interface.
 */
export function instanceOfGetIdxOfFileResponse(value: object): value is GetIdxOfFileResponse {
    if (!('idx' in value) || value['idx'] === undefined) return false;
    return true;
}

export function GetIdxOfFileResponseFromJSON(json: any): GetIdxOfFileResponse {
    return GetIdxOfFileResponseFromJSONTyped(json, false);
}

export function GetIdxOfFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIdxOfFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'idx': json['idx'],
    };
}

export function GetIdxOfFileResponseToJSON(value?: GetIdxOfFileResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idx': value['idx'],
    };
}

