/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetIdxOfFileReqeust
 */
export interface GetIdxOfFileReqeust {
    /**
     * 
     * @type {number}
     * @memberof GetIdxOfFileReqeust
     */
    fileId: number;
}

/**
 * Check if a given object implements the GetIdxOfFileReqeust interface.
 */
export function instanceOfGetIdxOfFileReqeust(value: object): value is GetIdxOfFileReqeust {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function GetIdxOfFileReqeustFromJSON(json: any): GetIdxOfFileReqeust {
    return GetIdxOfFileReqeustFromJSONTyped(json, false);
}

export function GetIdxOfFileReqeustFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIdxOfFileReqeust {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'],
    };
}

export function GetIdxOfFileReqeustToJSON(value?: GetIdxOfFileReqeust | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file_id': value['fileId'],
    };
}

